name: Keep Database Alive

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:       

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend to keep database active
        run: curl -f https://ikonex-school-management-application.onrender.com/api/streams
